"""

Revision ID: 09a89a46485a
Revises: 3d80d85b827a
Create Date: 2020-06-08 03:43:32.436538

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09a89a46485a'
down_revision = '3d80d85b827a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('environment', schema=None) as batch_op:
        batch_op.drop_column('ip')
        batch_op.drop_column('machine')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('environment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('machine', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('ip', sa.TEXT(), nullable=True))

    # ### end Alembic commands ###
