"""

Revision ID: 3d80d85b827a
Revises: edba85e2041b
Create Date: 2020-06-08 03:23:19.335612

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d80d85b827a'
down_revision = 'edba85e2041b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('environment', sa.Column('server_machine', sa.Text(), nullable=True))
    op.add_column('environment', sa.Column('terminal_machine', sa.Text(), nullable=True))
    op.drop_column('environment', 'ip')
    op.drop_column('environment', 'machine')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('environment', sa.Column('machine', sa.TEXT(), nullable=True))
    op.add_column('environment', sa.Column('ip', sa.TEXT(), nullable=True))
    op.drop_column('environment', 'terminal_machine')
    op.drop_column('environment', 'server_machine')
    # ### end Alembic commands ###
