"""

Revision ID: 70aa6fb8c0d4
Revises: da004423bbc8
Create Date: 2020-06-30 02:06:50.131503

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70aa6fb8c0d4'
down_revision = 'da004423bbc8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tla', schema=None) as batch_op:
        batch_op.add_column(sa.Column('owner', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tla', schema=None) as batch_op:
        batch_op.drop_column('owner')

    # ### end Alembic commands ###
