"""task update

Revision ID: c632f9900550
Revises: 70aa6fb8c0d4
Create Date: 2020-10-09 03:19:08.236187

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c632f9900550'
down_revision = '70aa6fb8c0d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('assigner', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('env', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.drop_column('env')
        batch_op.drop_column('assigner')

    # ### end Alembic commands ###
