"""

Revision ID: d460cbf8b859
Revises: 09a89a46485a
Create Date: 2020-06-09 03:10:17.483855

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd460cbf8b859'
down_revision = '09a89a46485a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('compliance_report',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tla', sa.Text(), nullable=True),
    sa.Column('deployment_type', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), nullable=True),
    sa.Column('is_respond', sa.Text(), nullable=True),
    sa.Column('ticket', sa.Text(), nullable=True),
    sa.Column('small_file', sa.Text(), nullable=True),
    sa.Column('task', sa.Text(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('compliance_report')
    # ### end Alembic commands ###
