"""

Revision ID: da004423bbc8
Revises: d460cbf8b859
Create Date: 2020-06-12 03:10:48.686509

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da004423bbc8'
down_revision = 'd460cbf8b859'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('environment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('monitored_by', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('environment', schema=None) as batch_op:
        batch_op.drop_column('monitored_by')

    # ### end Alembic commands ###
