"""

Revision ID: db7cc0d488c1
Revises: 
Create Date: 2020-06-04 02:31:17.917342

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db7cc0d488c1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('crontab',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tla', sa.Text(), nullable=True),
    sa.Column('deployment_type', sa.Text(), nullable=True),
    sa.Column('machine_name', sa.Text(), nullable=True),
    sa.Column('ip', sa.Text(), nullable=True),
    sa.Column('crontab_name', sa.Text(), nullable=True),
    sa.Column('minute', sa.Text(), nullable=True),
    sa.Column('hour', sa.Text(), nullable=True),
    sa.Column('day', sa.Text(), nullable=True),
    sa.Column('month', sa.Text(), nullable=True),
    sa.Column('wday', sa.Text(), nullable=True),
    sa.Column('command', sa.Text(), nullable=True),
    sa.Column('enabled', sa.Text(), nullable=True),
    sa.Column('key_words', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('environment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tla', sa.Text(), nullable=True),
    sa.Column('deployment_type', sa.Text(), nullable=True),
    sa.Column('server_type', sa.Text(), nullable=True),
    sa.Column('machine', sa.Text(), nullable=True),
    sa.Column('ip', sa.Text(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('enabled', sa.Text(), nullable=True),
    sa.Column('key_words', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('issue',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tla', sa.Text(), nullable=True),
    sa.Column('ticket_type', sa.Text(), nullable=True),
    sa.Column('ticket_number', sa.Text(), nullable=True),
    sa.Column('begin_time', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('enabled', sa.Text(), nullable=True),
    sa.Column('key_words', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('regulation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tla', sa.Text(), nullable=True),
    sa.Column('reporter', sa.Text(), nullable=True),
    sa.Column('begin_time', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('enabled', sa.Text(), nullable=True),
    sa.Column('key_words', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rutineopt',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tla', sa.Text(), nullable=True),
    sa.Column('reporter', sa.Text(), nullable=True),
    sa.Column('begin_time', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('enabled', sa.Text(), nullable=True),
    sa.Column('key_words', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('schedule',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tla', sa.Text(), nullable=True),
    sa.Column('datetime', sa.Text(), nullable=True),
    sa.Column('command', sa.Text(), nullable=True),
    sa.Column('crontab', sa.Text(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('key_words', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('staff',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('staff_type', sa.Text(), nullable=True),
    sa.Column('tla', sa.Text(), nullable=True),
    sa.Column('escalation', sa.Text(), nullable=True),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('user_id', sa.Text(), nullable=True),
    sa.Column('role', sa.Text(), nullable=True),
    sa.Column('company_division', sa.Text(), nullable=True),
    sa.Column('email', sa.Text(), nullable=True),
    sa.Column('phone', sa.Text(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('enabled', sa.Text(), nullable=True),
    sa.Column('key_words', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('task',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tla', sa.Text(), nullable=True),
    sa.Column('ticket_type', sa.Text(), nullable=True),
    sa.Column('ticket_number', sa.Text(), nullable=True),
    sa.Column('begin_time', sa.Text(), nullable=True),
    sa.Column('end_time', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('enabled', sa.Text(), nullable=True),
    sa.Column('key_words', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tla',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tla', sa.Text(), nullable=True),
    sa.Column('customer_name', sa.Text(), nullable=True),
    sa.Column('solution', sa.Text(), nullable=True),
    sa.Column('runbook_url', sa.Text(), nullable=True),
    sa.Column('tl', sa.Text(), nullable=True),
    sa.Column('project_code', sa.Text(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('enabled', sa.Text(), nullable=True),
    sa.Column('key_words', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tla')
    op.drop_table('task')
    op.drop_table('staff')
    op.drop_table('schedule')
    op.drop_table('rutineopt')
    op.drop_table('regulation')
    op.drop_table('issue')
    op.drop_table('environment')
    op.drop_table('crontab')
    # ### end Alembic commands ###
