"""

Revision ID: edba85e2041b
Revises: db7cc0d488c1
Create Date: 2020-06-08 02:49:07.663026

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'edba85e2041b'
down_revision = 'db7cc0d488c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('environment', sa.Column('is_compliance', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('environment', 'is_compliance')
    # ### end Alembic commands ###
