"""update Regulation

Revision ID: f7bd721dafa1
Revises: b99e20954a7c
Create Date: 2020-10-26 05:14:09.322703

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f7bd721dafa1'
down_revision = 'b99e20954a7c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('regulation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('end_time', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('solution', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('summary', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('regulation', schema=None) as batch_op:
        batch_op.drop_column('summary')
        batch_op.drop_column('solution')
        batch_op.drop_column('end_time')

    # ### end Alembic commands ###
